name: Run Shared Script
description: Runs the shared bash script in Repo A

runs:
  using: "composite"
  steps:
    - name: Checkout repo
        uses: actions/checkout@v4
    - name: Run script
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/run.sh
        ${{ github.action_path }}/run.sh
