name: Enforce CODEOWNERS

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: read

jobs:
  enforce:
    uses: ./.github/workflows/code_owners_composite.yaml
