name: Run Script Reusable Workflow

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

permissions:
  contents: read

jobs:
  run-script-job:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout Repo A (vamsee33/cloudposse)
        uses: actions/checkout@v4
        with:
          repository: vamsee33/cloudposse
          token: ${{ steps.generate_token.outputs.token }}
          ref: main
          path: repo-a

      - name: Run script from Repo A
        run: |
          chmod +x repo-a/scripts/run.sh
          ./repo-a/scripts/run.sh

      - name: Test GitHub API call
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "Calling GitHub API..."
          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/commits \
               | jq '.[0]'
