name: Run Script Reusable Workflow

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

permissions:
  contents: read

jobs:
  run-script-job:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Debug generated token length
        run: echo "Token length: ${{ steps.generate_token.outputs.token && steps.generate_token.outputs.token.length || 'no token' }}"

      - name: Test API access with generated token
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "Testing API access for vamsee33/cloudposse..."
          curl -s -o /dev/null -w "%{http_code}\n" -H "Authorization: Bearer $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/vamsee33/cloudposse

      - name: Checkout Repo A (with debug)
        uses: actions/checkout@v4
        with:
          repository: vamsee33/cloudposse
          token: ${{ steps.generate_token.outputs.token }}
          ref: main
         
        env:
          GIT_TRACE: 1
          GIT_CURL_VERBOSE: 1

      - name: List files in repo-a
        run: ls -l 

      - name: Run script from local action
        uses: ./.github/actions/run-script

      - name: GitHub API call using generated token
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "🔐 Calling GitHub API with GH_TOKEN..."
          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/commits | jq '.[0]'
