name: Run Hardcoded Script from This Repo

on:
  workflow_call:
    secrets:
      GH_APP_TOKEN:
        required: true

jobs:
  run-script-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout calling repo (Repo B)
        uses: actions/checkout@v4

      - name: Clone reusable workflow repo (Repo A)
        run: |
          git clone https://x-access-token:${{ secrets.GH_APP_TOKEN }}@github.com/<your-org-or-username>/repo-a.git reusable-repo

      - name: Make script executable
        run: chmod +x reusable-repo/scripts/run.sh

      - name: Run the script
        run: ./reusable-repo/scripts/run.sh

      - name: GitHub API call using GH_APP_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GH_APP_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/commits | jq '.[0]'
